server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: ${EUREKA_URL:${eureka.instance.hostname}:${server.port}/eureka/}
    fetch-registry: false
    register-with-eureka: false
