spring:
  application:
    name: toy-zuul
server:
  port: 8095
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    enabled: true
zuul:
  ignoredServices: '*'  # routes에 정의되지 않은 모든 요청은 무시 함
  sensitive-headers:    # header의 모든 정보를 bypass 함
  # prefix: /api
  routes:
    toy-api:
      path: /toy/**
      service-id: toy-api
      strip-prefix: true
hystrix:
  command:
#    toy-api:
#      execution:
#        isolation:
#          thread:
#            # Ribbon의 각 timeout보다 커야 기대하는대로 동작함
#            # 설정 시간동안 처리 지연발생시 timeout and 설정한 fallback 로직 수행
#            timeoutInMilliseconds: 60000
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
#toy-api:
#  ribbon:
#    ConnectTimeout: 3000
#    ReadTimeout: 60000
